# .github/workflows/daily_update.yml (最终的、分步诊断版)

name: Daily Stock Data Update - Diagnostic

on:
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ===================================================================
      # 核心诊断步骤：我们在 Actions 里，一步一步地模拟 worker.py 的执行
      # ===================================================================
      - name: 1. Test Python and Imports
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "--- Testing basic python execution ---"
          python --version
          echo "--- Testing imports ---"
          python -c "import os, sys, time, pandas, numpy, pandas_ta, MyTT"
          echo "Basic imports OK."
          python -c "from supabase import create_client, Client"
          echo "Supabase import OK."
          # 我们把最可疑的 AKShare 单独测试
          python -c "import akshare as ak"
          echo "AKShare import OK."

      - name: 2. Test AKShare data fetching
        run: |
          echo "--- Testing AKShare single stock fetch ---"
          # 使用 -c 参数，直接在命令行运行一小段 Python 代码
          python -c "import akshare as ak; print(ak.stock_zh_a_hist(symbol='000001', period='daily', start_date='20250912', end_date='20250912'))"

      - name: 3. Run the full worker script
        if: always() # 无论前面是否失败，都尝试运行一次主脚本
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python worker.py
