name: 2. Update Daily Metrics
on:
  schedule:
    - cron: '15 18 * * 1-5' # 每天 02:15 (北京时间) 启动，错开一点
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: { python-version: '3.12' }
      - run: pip install -r requirements.txt
      - name: Run update_daily_metrics.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python scripts/update_daily_metrics.py
